### ISSUE TITLE
Missing the rest of the files that compose the theme

### ISSUE THREAD

**Issue by mariojuniorjp** [anshicat/dotfiles#2]
Hey buddy! I would like you to provide the complete theme? I am looking to apply on my desktop, but the available files do not work.

Thanks! :D

**Comment by anshicat** [comment]
for awesome wm?

**Comment by mariojuniorjp** [comment]
Look: http://webmshare.com/play/MnYrZ

When I apply the theme in awesome, remains the Vanilla theme and appear several errors indicating that you are missing a lot of things.

Actually, this desktop that appears in the video is yours? I would like to configure my the same way. 

As soon as I turn on the computer I will send you the error logs. ;)

**Comment by anshicat** [comment]
Sounds like you're probably just missing the dependencies for the configuration. Read the "requires" section of the rc file, right at the top, and install those

**Comment by mariojuniorjp** [comment]
Thanks so much, anon! 😊
